Update: publish.yml and go up to Version v0.30.8

diff --git a/.github/workflows/publish.yml b/.github/workflows/publish.yml
--- a/.github/workflows/publish.yml
+++ b/.github/workflows/publish.yml
@@ -5,7 +5,7 @@ on:
     types: [published]
 
 jobs:
-  publish-package:
+  publish:
     runs-on: ubuntu-latest
     permissions:
       contents: read
@@ -19,16 +19,30 @@ jobs:
         with:
           python-version: '3.x'
 
-      - name: Install build tool
-        run: pip install build
+      - name: Install dependencies
+        run: |
+          python -m pip install --upgrade pip
+          pip install build twine
 
       - name: Build package
         run: python -m build
 
-      - name: Publish to GitHub Packages
-        uses: pypa/gh-action-pypi-publish@release/v1
-        with:
-          user: ${{ github.actor }}
-          password: ${{ secrets.MY_PAT }}
-          repository_url: https://pypi.pkg.github.com/mariosergiosl/
-          skip_existing: true
+      - name: Publish to GitHub Packages (Manual Twine)
+        env:
+          TWINE_USERNAME: mariosergiosl
+          TWINE_PASSWORD: ${{ secrets.MY_PAT }}
+          TWINE_REPOSITORY_URL: https://pypi.pkg.github.com/mariosergiosl/
+        run: |
+          echo "--- DEBUG INFO ---"
+          if [ -z "$TWINE_PASSWORD" ]; then
+            echo "ERRO!: The secret 'MY_PAT' is empty or not found!"
+            echo "Verifique em Settings -> Secrets and variables -> Actions."
+            exit 1
+          else
+            echo "OK!: The secret 'MY_PAT' load (size: ${#TWINE_PASSWORD} caracters)."
+          fi
+          echo "Try upload to: $TWINE_REPOSITORY_URL"
+          echo "------------------"
+
+          echo "Starting upload to $TWINE_REPOSITORY_URL..."
+          twine upload --verbose dist/*
